/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;
import java.sql.ResultSet;
import static UI.HappyTravel.base;
import java.util.Random;


public class Consultas extends javax.swing.JPanel {

    /**
     * Creates new form Consultas
     */
    
    

    public Consultas() {
        initComponents();
    }
    
    public void iniciar(int index){
        ResultSet resultados = base.consultar("SELECT a.IDCLIENTES,a.NOMBRE, a.APELLIDOS,\n" +
"b.DESTINO,\n" +
"b.FECHALLEGADA,\n" +
"b.FECHASALIDA,\n" +
"b.AUTOBUS,\n" +
"b.NOMBREHOTEL,\n" +
"b.NINOS,\n" +
"b.ADULTOS,\n" +
"c.NUMHAB,\n" +
"c.TIPOHAB,\n" +
"c.SERVICIOHOTEL \n" +
"FROM APP.CLIENTES a, APP.RESERVAS b , APP.HOTELRESERVAS c\n" +
"WHERE (a.IDCLIENTES="+index+" and b.IDCLIENTES="+index+" and c.IDCLIENTES="+index+")");
        if (resultados != null) {
            try {
                while (resultados.next()) {
                    jAdultos.setText(resultados.getString("ADULTOS"));
                    jApellidos.setText(resultados.getString("APELLIDOS"));
                    jAutobus.setText(resultados.getString("AUTOBUS"));
                    jDestino.setText(resultados.getString("DESTINO"));
                    jHotel.setText(resultados.getString("NOMBREHOTEL"));
                    jIDcliente.setText(resultados.getString("IDCLIENTES"));
                    jLlegada.setText(resultados.getString("FECHALLEGADA"));
                    jNinios.setText(resultados.getString("NINOS"));
                    jNombre.setText(resultados.getString("NOMBRE"));
                    jSalida.setText(resultados.getString("FECHASALIDA"));
                    jServicios.setText(resultados.getString("SERVICIOHOTEL"));
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        Random rnd = new Random();
        
        jTotal.setText("$"+String.valueOf(rnd.nextInt(1000)+3000));
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jDestino = new javax.swing.JTextField();
        jAutobus = new javax.swing.JTextField();
        jSalida = new javax.swing.JTextField();
        jLlegada = new javax.swing.JTextField();
        jNinios = new javax.swing.JTextField();
        jAdultos = new javax.swing.JTextField();
        jHotel = new javax.swing.JTextField();
        jTotal = new javax.swing.JTextField();
        jServicios = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jNombre = new javax.swing.JTextField();
        jApellidos = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jIDcliente = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(244, 192, 119));
        setForeground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(600, 400));
        setMinimumSize(new java.awt.Dimension(600, 400));
        setPreferredSize(new java.awt.Dimension(600, 400));

        jLabel2.setFont(new java.awt.Font("HP Simplified Light", 1, 14)); // NOI18N
        jLabel2.setText("Destino");

        jLabel3.setFont(new java.awt.Font("HP Simplified Light", 1, 14)); // NOI18N
        jLabel3.setText("Transporte");

        jLabel4.setFont(new java.awt.Font("HP Simplified Light", 1, 14)); // NOI18N
        jLabel4.setText("Fecha de salida");

        jLabel5.setFont(new java.awt.Font("HP Simplified Light", 1, 14)); // NOI18N
        jLabel5.setText("Fecha de llegada");

        jLabel6.setFont(new java.awt.Font("HP Simplified Light", 1, 14)); // NOI18N
        jLabel6.setText("Niños");

        jLabel7.setFont(new java.awt.Font("HP Simplified Light", 1, 14)); // NOI18N
        jLabel7.setText("Adultos");

        jLabel8.setFont(new java.awt.Font("HP Simplified Light", 1, 14)); // NOI18N
        jLabel8.setText("Hotel");

        jLabel9.setFont(new java.awt.Font("HP Simplified Light", 1, 14)); // NOI18N
        jLabel9.setText("TOTAL");

        jLabel10.setFont(new java.awt.Font("HP Simplified Light", 1, 14)); // NOI18N
        jLabel10.setText("Servicios ");

        jDestino.setEditable(false);
        jDestino.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jDestino.setToolTipText("");
        jDestino.setMaximumSize(new java.awt.Dimension(14, 27));
        jDestino.setPreferredSize(new java.awt.Dimension(14, 24));

        jAutobus.setEditable(false);
        jAutobus.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jAutobus.setToolTipText("");
        jAutobus.setMinimumSize(new java.awt.Dimension(14, 24));

        jSalida.setEditable(false);
        jSalida.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jSalida.setToolTipText("");
        jSalida.setMaximumSize(new java.awt.Dimension(14, 27));

        jLlegada.setEditable(false);
        jLlegada.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jLlegada.setToolTipText("");
        jLlegada.setMaximumSize(new java.awt.Dimension(14, 27));

        jNinios.setEditable(false);
        jNinios.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jNinios.setToolTipText("");
        jNinios.setMaximumSize(new java.awt.Dimension(40, 27));
        jNinios.setMinimumSize(new java.awt.Dimension(40, 27));

        jAdultos.setEditable(false);
        jAdultos.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jAdultos.setToolTipText("");
        jAdultos.setMaximumSize(new java.awt.Dimension(40, 27));
        jAdultos.setMinimumSize(new java.awt.Dimension(40, 27));

        jHotel.setEditable(false);
        jHotel.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jHotel.setToolTipText("");
        jHotel.setMaximumSize(new java.awt.Dimension(14, 27));

        jTotal.setEditable(false);
        jTotal.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jTotal.setToolTipText("");

        jServicios.setEditable(false);
        jServicios.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jServicios.setToolTipText("");

        jPanel5.setBackground(new java.awt.Color(228, 137, 121));

        jLabel15.setBackground(new java.awt.Color(0, 255, 204));
        jLabel15.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 51, 204));
        jLabel15.setText("Consultas");

        jPanel7.setBackground(new java.awt.Color(244, 192, 119));

        jNombre.setEditable(false);
        jNombre.setBackground(new java.awt.Color(255, 255, 255));
        jNombre.setToolTipText("Nombre");
        jNombre.setMinimumSize(new java.awt.Dimension(14, 27));
        jNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNombreActionPerformed(evt);
            }
        });

        jApellidos.setEditable(false);
        jApellidos.setBackground(new java.awt.Color(255, 255, 255));
        jApellidos.setToolTipText("Apellidos");
        jApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jApellidosActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("HP Simplified Light", 1, 14)); // NOI18N
        jLabel1.setText("ID del cliente");

        jIDcliente.setToolTipText("Aqui puedes ingresar el ID del cliente");
        jIDcliente.setMaximumSize(new java.awt.Dimension(74, 27));
        jIDcliente.setMinimumSize(new java.awt.Dimension(74, 27));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jIDcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jIDcliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(8, 8, 8)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel16.setFont(new java.awt.Font("HP Simplified Light", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));

        jButton1.setBackground(new java.awt.Color(41, 127, 184));
        jButton1.setText("Iniciar consulta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel16)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(114, 114, 114)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jSalida, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jDestino, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jNinios, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jAdultos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTotal))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jAutobus, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                    .addComponent(jLlegada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jServicios, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))))
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jAdultos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jNinios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jAutobus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel8)
                        .addComponent(jHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(jServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jButton1))
                .addGap(42, 42, 42)
                .addComponent(jLabel16)
                .addGap(164, 164, 164))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNombreActionPerformed

    private void jApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jApellidosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ResultSet resultados = HappyTravel.base.consultar("SELECT max(IDCLIENTES) as maximo FROM APP.CLIENTES");
            
        int i = 0,j=0;
        if (resultados != null) {
                try {
                    while (resultados.next()) {
                        i = Integer.parseInt(resultados.getString("maximo"));
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        int index=0;
        
        if(!"".equals(jIDcliente.getText())){
            index=Integer.parseInt(jIDcliente.getText());
            iniciar(index);
        }else{
            iniciar(i);
        }
        
        //iniciar();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jAdultos;
    private javax.swing.JTextField jApellidos;
    private javax.swing.JTextField jAutobus;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jDestino;
    private javax.swing.JTextField jHotel;
    private javax.swing.JTextField jIDcliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jLlegada;
    private javax.swing.JTextField jNinios;
    private javax.swing.JTextField jNombre;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField jSalida;
    private javax.swing.JTextField jServicios;
    private javax.swing.JTextField jTotal;
    // End of variables declaration//GEN-END:variables
}
