/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import BD.Conexion;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import static java.lang.Thread.sleep;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;

/**
 *
 * @author jklm2
 */
public class HappyTravel extends javax.swing.JFrame {
    
    
    public static Conexion base = new Conexion();

    /**
     * Creates new form HappyTravel
     */
    public HappyTravel() {
        base.conectar();
        
        
        try {
            Thread.sleep(100);
            initComponents();
            hotel1.setVisible(false);
            consultas1.setVisible(false);
            registro1.setVisible(false);
            reservacion1.setVisible(false);
            
            //icono
            setIconImage(new ImageIcon(getClass().getResource("/Imagenes/logo123.png")).getImage());
            
            //Fondo
            ((JPanel)getContentPane()).setOpaque(false);
            ImageIcon uno=new ImageIcon(this.getClass().getResource("/Imagenes/fondo.jpg"));
            JLabel fondo= new JLabel();
            fondo.setIcon(uno);
            getLayeredPane().add(fondo,JLayeredPane.FRAME_CONTENT_LAYER);
            fondo.setBounds(0,0,uno.getIconWidth(),uno.getIconHeight());
        } catch (InterruptedException ex) {
            Logger.getLogger(HappyTravel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jBtnReservas = new javax.swing.JButton();
        jBtnRegistro = new javax.swing.JButton();
        jBtnConsultas = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        registro1 = new UI.Registro();
        reservacion1 = new UI.Reservacion();
        consultas1 = new UI.Consultas();
        hotel1 = new UI.Hotel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Happy Travel");
        setBackground(new java.awt.Color(105, 1, 90));
        setIconImages(null);
        setLocation(new java.awt.Point(100, 100));
        setMinimumSize(new java.awt.Dimension(900, 600));
        setResizable(false);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("HP Simplified Light", 1, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo123.png"))); // NOI18N

        jBtnReservas.setBackground(new java.awt.Color(153, 51, 255));
        jBtnReservas.setFont(new java.awt.Font("HP Simplified Light", 1, 14)); // NOI18N
        jBtnReservas.setForeground(new java.awt.Color(255, 255, 255));
        jBtnReservas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Res2.png"))); // NOI18N
        jBtnReservas.setBorder(null);
        jBtnReservas.setBorderPainted(false);
        jBtnReservas.setContentAreaFilled(false);
        jBtnReservas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnReservas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnReservas.setIconTextGap(-3);
        jBtnReservas.setNextFocusableComponent(jBtnConsultas);
        jBtnReservas.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Res3.png"))); // NOI18N
        jBtnReservas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Res1.png"))); // NOI18N
        jBtnReservas.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jBtnReservas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnReservasActionPerformed(evt);
            }
        });

        jBtnRegistro.setBackground(new java.awt.Color(138, 35, 240));
        jBtnRegistro.setFont(new java.awt.Font("HP Simplified Light", 1, 14)); // NOI18N
        jBtnRegistro.setForeground(new java.awt.Color(255, 255, 255));
        jBtnRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Re2.png"))); // NOI18N
        jBtnRegistro.setBorder(null);
        jBtnRegistro.setBorderPainted(false);
        jBtnRegistro.setContentAreaFilled(false);
        jBtnRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnRegistro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnRegistro.setIconTextGap(-3);
        jBtnRegistro.setNextFocusableComponent(jBtnReservas);
        jBtnRegistro.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Re3.png"))); // NOI18N
        jBtnRegistro.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Re1.png"))); // NOI18N
        jBtnRegistro.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jBtnRegistro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRegistroActionPerformed(evt);
            }
        });

        jBtnConsultas.setBackground(new java.awt.Color(162, 100, 224));
        jBtnConsultas.setFont(new java.awt.Font("HP Simplified Light", 1, 14)); // NOI18N
        jBtnConsultas.setForeground(new java.awt.Color(255, 255, 255));
        jBtnConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Co2.png"))); // NOI18N
        jBtnConsultas.setBorder(null);
        jBtnConsultas.setBorderPainted(false);
        jBtnConsultas.setContentAreaFilled(false);
        jBtnConsultas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnConsultas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnConsultas.setIconTextGap(-3);
        jBtnConsultas.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Co3.png"))); // NOI18N
        jBtnConsultas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Co1.png"))); // NOI18N
        jBtnConsultas.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jBtnConsultas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConsultasActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 158, 171));
        jPanel1.setMaximumSize(new java.awt.Dimension(600, 400));
        jPanel1.setMinimumSize(new java.awt.Dimension(600, 400));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 400));

        reservacion1.setPreferredSize(new java.awt.Dimension(600, 400));

        hotel1.setEnabled(false);
        hotel1.setPreferredSize(new java.awt.Dimension(600, 400));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(registro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(reservacion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(consultas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(hotel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(registro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(reservacion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(consultas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(hotel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBtnReservas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnConsultas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jBtnRegistro)
                        .addGap(46, 46, 46)
                        .addComponent(jBtnReservas)
                        .addGap(37, 37, 37)
                        .addComponent(jBtnConsultas)
                        .addContainerGap(74, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnReservasActionPerformed
        registro1.setVisible(false);
        hotel1.setVisible(false);
        consultas1.setVisible(false);
        reservacion1.setVisible(true);
    }//GEN-LAST:event_jBtnReservasActionPerformed

    
    private void jBtnConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConsultasActionPerformed
        registro1.setVisible(false);
        hotel1.setVisible(false);
        consultas1.setVisible(true);
        reservacion1.setVisible(false);
    }//GEN-LAST:event_jBtnConsultasActionPerformed

    private void jBtnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRegistroActionPerformed
        hotel1.setVisible(false);
        consultas1.setVisible(false);
        registro1.setVisible(true);
        reservacion1.setVisible(false);
    }//GEN-LAST:event_jBtnRegistroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HappyTravel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HappyTravel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HappyTravel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HappyTravel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //JOptionPane.showMessageDialog(null, "sadfasdfasdf");
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    Thread.sleep(100);
                    new HappyTravel().setVisible(true);
                } catch (InterruptedException ex) {
                    Logger.getLogger(HappyTravel.class.getName()).log(Level.SEVERE, null, ex);
                }
                //Thread.sleep(3000);
                
            }
        });
    }

    private javax.swing.JFrame jFrCarga;
    //private javax.swing.JPanel jPanCarga;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private UI.Consultas consultas1;
    public static UI.Hotel hotel1;
    private javax.swing.JButton jBtnConsultas;
    private javax.swing.JButton jBtnRegistro;
    private javax.swing.JButton jBtnReservas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private UI.Registro registro1;
    private UI.Reservacion reservacion1;
    // End of variables declaration//GEN-END:variables
}
