
package UI;

import com.toedter.calendar.JDateChooser;
import java.util.Date;
import java.util.Random;
import java.sql.ResultSet;
import static UI.HappyTravel.base;

/**
 *
 * @author Montse
 */

public class Hotel extends javax.swing.JPanel {

    /**
     * Creates new form Hotel
     */
    public Hotel() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        list1 = new java.awt.List();
        jPanel1 = new javax.swing.JPanel();
        jHabitacion = new javax.swing.JComboBox<>();
        jTipoHab = new javax.swing.JComboBox<>();
        jServicio = new javax.swing.JComboBox<>();
        jBtnConcluir = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();

        list1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list1ActionPerformed(evt);
            }
        });

        setMaximumSize(new java.awt.Dimension(600, 400));
        setMinimumSize(new java.awt.Dimension(600, 400));

        jPanel1.setBackground(new java.awt.Color(244, 192, 119));
        jPanel1.setMaximumSize(new java.awt.Dimension(400, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 600));

        jHabitacion.setFont(new java.awt.Font("HP Simplified Light", 0, 14)); // NOI18N
        jHabitacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Habitación", "Grande", "Mediana", "Chica" }));

        jTipoHab.setFont(new java.awt.Font("HP Simplified Light", 0, 14)); // NOI18N
        jTipoHab.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo de Habitación", "Individual", "Doble", "Triple", "Queen", "King", "Suit" }));

        jServicio.setFont(new java.awt.Font("HP Simplified Light", 0, 14)); // NOI18N
        jServicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Servicio", "Completo", "Simple" }));

        jBtnConcluir.setBackground(new java.awt.Color(41, 127, 184));
        jBtnConcluir.setFont(new java.awt.Font("HP Simplified Light", 1, 14)); // NOI18N
        jBtnConcluir.setText("Concluir");
        jBtnConcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConcluirActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(228, 137, 121));

        jLabel15.setBackground(new java.awt.Color(0, 255, 204));
        jLabel15.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 51, 204));
        jLabel15.setText("Hoteles HappyTravel");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(151, 151, 151))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(jTipoHab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(jHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnConcluir)
                            .addComponent(jServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(71, 292, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jTipoHab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98)
                .addComponent(jBtnConcluir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void list1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_list1ActionPerformed

    private void jBtnConcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConcluirActionPerformed
        /*
        INSERT INTO APP.HOTELRESERVAS (IDHOTEL, NOMBREHOTEL, NUMHAB, TIPOHAB, SERVICIOHOTEL, IDCLIENTES) 
	VALUES (2, NULL, NULL, NULL, NULL, NULL)
        */
        
        ResultSet resultados = HappyTravel.base.consultar("SELECT max(IDHOTEL) as maximo FROM APP.HOTELRESERVAS");
        ResultSet resultados2 = HappyTravel.base.consultar("SELECT max(IDCLIENTES) as maximo FROM APP.CLIENTES");
            
        int i = 0,j=0;
        if (resultados != null) {
                try {
                    while (resultados.next()) {
                        i = Integer.parseInt(resultados.getString("maximo"));
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        
        if (resultados2 != null) {
                try {
                    while (resultados2.next()) {
                        j = Integer.parseInt(resultados2.getString("maximo"));
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        
        if (HappyTravel.base.ejecutar("INSERT INTO APP.HOTELRESERVAS (IDHOTEL, "
                + "NOMBREHOTEL, "
                + "NUMHAB, "
                + "TIPOHAB, "
                + "SERVICIOHOTEL, "
                + "IDCLIENTES) \n" 
                + "VALUES (" + (i + 1) + ", "
                + "'" + Reservacion.jComHotel.getSelectedItem() + "', "
                + ""+jHabitacion.getSelectedIndex()+", "
                + "'"+jTipoHab.getSelectedItem()+"', "
                + "'"+jServicio.getSelectedItem()+"', "
                + ""+j+")")){
            System.out.println("eEjecución correcta!");
            this.setVisible(false);
        }
else {
        System.out.println("Ocurrió un problema al ejecutar!");
        }
        
    }//GEN-LAST:event_jBtnConcluirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnConcluir;
    private javax.swing.JComboBox<String> jHabitacion;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JComboBox<String> jServicio;
    private javax.swing.JComboBox<String> jTipoHab;
    private java.awt.List list1;
    // End of variables declaration//GEN-END:variables
}
